//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json.Linq;
using System.Text;


namespace DL
{
    using System;
    using System.Collections.Generic;

    public partial class Category
    {
        public Category()
        {
            this.Inventories = new HashSet<Inventory>();
        }

        public int categoryID { get; set; }
        public string categoryName { get; set; }
        public string imgUrl { get; set; }

        public virtual ICollection<Inventory> Inventories { get; set; }


        public JObject toJson()
        {

            String jsonString = "{'categoryID':'" + categoryID + "'," + "'categoryName':'" + categoryName + "'," + "'imgUrl':'" + imgUrl + "'}";
            JObject json = JObject.Parse(jsonString);
            return json;
        }
    }
}
