//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscrepancyDetail
    {
        public string discrepancyDetailsID { get; set; }
        public string discrepancyID { get; set; }
        public string inventoryCode { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
        public double totalAmount { get; set; }
        public string description { get; set; }
    
        public virtual Discrepancy Discrepancy { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
