//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discrepancy
    {
        public Discrepancy()
        {
            this.DiscrepancyDetails = new HashSet<DiscrepancyDetail>();
        }
    
        public string discrepancyID { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public int userID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<DiscrepancyDetail> DiscrepancyDetails { get; set; }
    }
}
