//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrice
    {
        public int itemPriceID { get; set; }
        public string inventoryCode { get; set; }
        public string supplierCode { get; set; }
        public double price { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
