//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortageDetail
    {
        public string shortageDetailsID { get; set; }
        public string shortageID { get; set; }
        public string inventoryCode { get; set; }
        public int quantity { get; set; }
        public string reason { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Shortage Shortage { get; set; }
    }
}
