//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.ItemPrices = new HashSet<ItemPrice>();
            this.Orders = new HashSet<Order>();
        }
    
        public string supplierCode { get; set; }
        public string name { get; set; }
        public string contactName { get; set; }
        public string phoneNo { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public string gstRegistrationNo { get; set; }
    
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
